-- CREATE ENUM TYPE user_role IF NOT EXISTS
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('admin','user');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(40) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role          user_role NOT NULL DEFAULT 'user',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS daily_prompt (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date"        DATE UNIQUE NOT NULL,
  sentence      TEXT NOT NULL,
  source_book   TEXT,
  source_author TEXT,
  source_id     TEXT,
  fetched_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prompt_id     BIGINT NOT NULL REFERENCES daily_prompt(id) ON DELETE CASCADE,
  user_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
  device_token  VARCHAR(64),
  ip_hash       VARCHAR(64),
  title         VARCHAR(100),
  content       TEXT NOT NULL,
  is_anonymous  BOOLEAN NOT NULL DEFAULT FALSE,
  word_count    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_story_user_per_day UNIQUE (prompt_id, user_id),
  CONSTRAINT uq_story_device_per_day UNIQUE (prompt_id, device_token)
);

CREATE INDEX IF NOT EXISTS idx_stories_prompt_created
  ON stories(prompt_id, created_at DESC);

-- FLOWERS (likes)
CREATE TABLE IF NOT EXISTS flowers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value      SMALLINT NOT NULL DEFAULT 1 CHECK (value IN (1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_flower UNIQUE (story_id, user_id)
);

