BEGIN;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id                 INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  public_id               UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  display_name            VARCHAR(40) UNIQUE NOT NULL,
  avatar_path             TEXT NULL,
  favorite_quote_sentence TEXT NULL,
  favorite_quote_book     TEXT NULL,
  favorite_quote_author   TEXT NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_display_name_not_blank CHECK (length(trim(display_name)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_public_id ON user_profiles(public_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_display_name ON user_profiles(display_name);

CREATE TABLE IF NOT EXISTS daily_prompt (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date"        DATE UNIQUE NOT NULL,
  sentence      TEXT NOT NULL,
  source_book   TEXT,
  source_author TEXT,
  source_id     TEXT,
  fetched_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stories (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id     UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  prompt_id     BIGINT NOT NULL REFERENCES daily_prompt(id) ON DELETE CASCADE,
  user_id       INTEGER REFERENCES users(id) ON DELETE SET NULL,
  title         VARCHAR(100),
  content       TEXT NOT NULL,
  is_anonymous  BOOLEAN NOT NULL DEFAULT FALSE,
  visibility    VARCHAR(16) NOT NULL DEFAULT 'public',
  word_count    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_story_user_per_day UNIQUE (prompt_id, user_id),
  CONSTRAINT stories_visibility_check CHECK (visibility IN ('public', 'private'))
);

CREATE INDEX IF NOT EXISTS idx_stories_public_id ON stories(public_id);
CREATE INDEX IF NOT EXISTS idx_stories_prompt_created ON stories(prompt_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stories_user ON stories(user_id);
CREATE INDEX IF NOT EXISTS idx_stories_user_created ON stories(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stories_public_prompt_created
  ON stories(prompt_id, created_at DESC)
  WHERE visibility = 'public';

CREATE TABLE IF NOT EXISTS flowers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value      SMALLINT NOT NULL DEFAULT 1 CHECK (value IN (1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_flower UNIQUE (story_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_flowers_story ON flowers(story_id);
CREATE INDEX IF NOT EXISTS idx_flowers_user ON flowers(user_id);

COMMIT;
